<?php namespace SchultenMedia\Vwe;

use Event;
use Backend;
use Cms\Classes\Theme;
use Cms\Classes\Controller as CmsController;
use System\Classes\PluginBase;

/**
 * Plugin Information File
 */
class Plugin extends PluginBase
{
    /**
     * @return array
     */
    public function pluginDetails()
    {
        return [
            'name'        => 'VWE doorlinkenvoorraad',
            'description' => 'Voorraad koppeling VWE',
            'author'      => 'SchultenMedia',
            'icon'        => 'icon-bullseye',
            'homepage'    => 'https://www.schultenmedia.nl'
        ];
    }

    public function boot()
    {
    }


    /**
     * Add event listeners
     */
    protected function addEventListeners()
    {

    }



    public function registerSettings()
    {
        return [
        ]; // TODO: Change the autogenerated stub
    }
}
